local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>la", mark.add_file)
vim.keymap.set("n", "<leader>ll", ui.toggle_quick_menu)
vim.keymap.set("n", "<leader>ls", function()
	ui.nav_file(1)
end)
vim.keymap.set("n", "<leader>ld", function()
	ui.nav_file(2)
end)
vim.keymap.set("n", "<leader>lf", function()
	ui.nav_file(3)
end)
